 {
     "button":[
     {	
          "name":"大赛指南",
          "sub_button":[
           {	
               "type":"click",
               "name":"创青春指南",
               "key":"TZB_GUIDE"
            },
            {	
               "type":"click",
               "name":"会务安排",
               "key":"TZB_MEETING"
            },
            {
               "type":"click",
               "name":"特别活动",
               "key":"TZB_ACTIVITY"
            }]
      },
      {	
          "name":"生活向导",
          "sub_button":[
           {	
               "type":"click",
               "name":"赛区导航",
               "key":"TZB_MAP"
            },
            {	
               "type":"click",
               "name":"温馨提示",
               "key":"TZB_WEATHER"
            },
            {	
               "type":"click",
               "name":"生活指南",
               "key":"TZB_AMUSE"
            },
            {
               "type":"click",
               "name":"联系我们",
               "key":"TZB_CONNECT"
            }]
      },
      {	
          "name":"创青春之路",
          "sub_button":[
           {	
               "type":"click",
               "name":"创政策",
               "key":"TZB_POLICY"
            },
            {	
               "type":"click",
               "name":"创青春达人",
               "key":"TZB_PERSON"
            },
            {	
               "type":"click",
               "name":"创team资讯",
               "key":"TZB_TEAM"
            },
            {
               "type":"click",
               "name":"图片汇编",
               "key":"TZB_PIC"
            }]
      }]
 }