 {
     "button":[
     {	
          "name":"大赛指南",
          "sub_button":[
           {	
               "type":"click",
               "name":"创青春指南",
               "key":"TZB_GUIDE"
            },
            {	
               "type":"click",
               "name":"会务安排",
               "key":"TZB_MEETING"
            },
            {
               "type":"click",
               "name":"特别活动",
               "key":"TZB_ACTIVITY"
            }]
      },
      {	
          "name":"生活向导",
          "sub_button":[
           {	
               "type":"click",
               "name":"赛区导航",
               "key":"TZB_MAP"
            },
            {	
               "type":"click",
               "name":"温馨提示",
               "key":"TZB_WEATHER"
            },
            {	
               "type":"click",
               "name":"生活指南",
               "key":"TZB_AMUSE"
            },
            {
               "type":"click",
               "name":"联系我们",
               "key":"TZB_CONNECT"
            }]
      },
      {	
          "name":"创青春之路",
          "sub_button":[
           {	
               "type":"click",
               "name":"创政策",
               "key":"TZB_POLICY"
            },
            {	
               "type":"click",
               "name":"创青春达人",
               "key":"TZB_PERSON"
            },
            {	
               "type":"click",
               "name":"创team资讯",
               "key":"TZB_TEAM"
            },
            {
               "type":"click",
               "name":"图片汇编",
               "key":"TZB_PIC"
            }]
      }]
 }
 
 
  {
     "button":[
     {	
          "type":"click",
           "name":"大赛指南",
            "key":"TZB_ZN"
      },
      {	
          "name":"生活向导",
          "sub_button":[
           {	
               "type":"click",
               "name":"赛区导航",
               "key":"TZB_MAP"
            },
            {	
               "type":"click",
               "name":"温馨提示",
               "key":"TZB_WEATHER"
            },
            {	
               "type":"view",
               "name":"生活指南",
               "url":"http://tzb-weixin.dhc.house/content.php?id=55"
            },
            {
               "type":"click",
               "name":"联系我们",
               "key":"TZB_CONNECT"
            }]
      },
      {	
          "name":"创青春之路",
          "sub_button":[
           {	
               "type":"view",
               "name":"我要代言",
               "url":"http://tzb-admin.dhc.house/comment/post"
            },
            {	
               "type":"view",
               "name":"精彩留言",
               "url":"http://tzb-admin.dhc.house/comment"
            }]
      }]
 }